---
- name: First Play - Docker Image Build
  hosts: docker
  tasks:
    - name: Copy Dockerfile
      copy:
       src: Dockerfile
       dest: /home/ansadmin/
    - name: Copy Artifact
      copy:
       src: target
       dest: /home/ansadmin
    - name : Build image
      command: docker build -t ashokit/mavenwebapp .
    - name : Push Docker Image
      command: docker push ashokit/mavenwebapp
- name: Second Play - K8s Deployment
  hosts: eks
  tasks:
   - name: Clone Git Repo
     git:
	  repo: https://github.com/ashokitschool/maven-web-app.git
	  branch: master     
   - name : K8S Deployment
     command: kubectl apply -f maven-web-app-deploy.yml
