# Write a playbook to ping all host nodes
---
- hosts: localhost
  tasks:
    - name: Ping All Host Nodes
      ping:
      remote_user: ansadmin
    - name: build docker image
      command: sudo docker build -t webapp .
