# Write a playbook to ping all host nodes
---
- hosts: docker
  tasks:
    - name: Copy Dockerfile
      copy:
       src: Dockerfile
       dest: /home/ansadmin/
    - name: Copy Artifact
      copy:
       src: target/
       dest: /home/ansadmin
    - name : Build image
      command: sudo docker build -t mavenwebapp .
    - name : Tag Docker image
      command: sudo docker tag mavenwebapp ashokit/mavenwebapp
