# Write a playbook to ping all host nodes
---
- hosts: localhost
  tasks:
    - name: build docker image
      command: docker build -t webapp .
    - name : tag image
      command: docker tag webapp ashokit/mavenwebapp
